package com.tamaraw.payroll.utils;

public enum Scenes {
    MAIN, EMPLOYEES, ADD_EMPLOYEES, EMPLOYEE_COMPENSATION, SETTINGS, DEDUCTION_TYPES, ADD_DEDUCTION_TYPES,
    INCOME_SETTINGS, ADD_INCOME_SETTINGS
}
